### ISSUE TITLE
Webpage for shellfish not available

### ISSUE THREAD

**Issue by vaqm2** [dandavison/shellfish#1]
Hi,

I was using the website as a frequent reference for usage but suddenly as of 28/09/2016, it looks like the webpage has been removed from the Oxford stats website.

http://www.stats.ox.ac.uk/~davison/software/shellfish/shellfish.php#sec-1

> Not Found
> 
> The requested URL /~davison/software/shellfish/shellfish.php was not found on this server.
> 
> Apache/2.2.22 (Debian) Server at www.stats.ox.ac.uk Port 80

**Comment by dandavison** [comment]
Hm, sorry about that. For now, can you use the PNG screenshot of the website which is in the README?

**Comment by vaqm2** [comment]
Thanks Dan, the screenshot helps!

**Comment by vaqm2** [comment]
Hi Dan,

Just wanted to check if you still have the HapMap SNP loading files for Illumina that were available for download on the webpage.

Thanks!

**Comment by dandavison** [comment]
I'm sorry, I do not have those to hand currently. I did contact the Oxford IT department who said they will be making archived content available to me at some point in the future. I'll post in this thread if I have those files to hand again.

**Comment by dandavison** [comment]
OK, they made the data available. The web page is now at http://dandavison.github.io/shellfish/ and the two data files are 
- http://dandavison.github.io/shellfish/snpload-aff.map.gz
- http://dandavison.github.io/shellfish/snpload-ill.map.gz
